use crate::_type::{Type, Types};

#[derive(Debug, Clone)]
pub enum Values {
    VOID,
    // using basic wrappers to make type casting way easier
    SIGNED(i64),
    UNSIGNED(u64),
    DECIMAL(f64),
    POINTER(usize),
    STRUCT, // TODO
    TYPE(Type),
    NAME(String),
}

#[derive(Debug, Clone)]
pub struct Value {
    pub main_type: Types,
    pub val: Values,
}

impl Values {
    pub fn add(&self, other: &Values) -> Values {
        match (self, other) {
            (Values::SIGNED(a), Values::SIGNED(b)) => Values::SIGNED(a + b),
            (Values::UNSIGNED(a), Values::UNSIGNED(b)) => Values::UNSIGNED(a + b),
            (Values::DECIMAL(a), Values::DECIMAL(b)) => Values::DECIMAL(a + b),
            (Values::SIGNED(a), Values::UNSIGNED(b)) => Values::SIGNED(*a + *b as i64),
            (Values::UNSIGNED(a), Values::SIGNED(b)) => Values::SIGNED(*a as i64 + *b),
            (Values::SIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 + b),
            (Values::UNSIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 + b),
            (Values::DECIMAL(a), Values::SIGNED(b)) => Values::DECIMAL(a + *b as f64),
            (Values::DECIMAL(a), Values::UNSIGNED(b)) => Values::DECIMAL(a + *b as f64),
            (Values::VOID, Values::VOID) => todo!(),
            (Values::VOID, Values::SIGNED(_)) => todo!(),
            (Values::VOID, Values::UNSIGNED(_)) => todo!(),
            (Values::VOID, Values::DECIMAL(_)) => todo!(),
            (Values::VOID, Values::POINTER(_)) => todo!(),
            (Values::VOID, Values::STRUCT) => todo!(),
            (Values::VOID, Values::TYPE(_)) => todo!(),
            (Values::VOID, Values::NAME(_)) => todo!(),
            (Values::SIGNED(_), Values::VOID) => todo!(),
            (Values::SIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::SIGNED(_), Values::STRUCT) => todo!(),
            (Values::SIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::SIGNED(_), Values::NAME(_)) => todo!(),
            (Values::UNSIGNED(_), Values::VOID) => todo!(),
            (Values::UNSIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::UNSIGNED(_), Values::STRUCT) => todo!(),
            (Values::UNSIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::UNSIGNED(_), Values::NAME(_)) => todo!(),
            (Values::DECIMAL(_), Values::VOID) => todo!(),
            (Values::DECIMAL(_), Values::POINTER(_)) => todo!(),
            (Values::DECIMAL(_), Values::STRUCT) => todo!(),
            (Values::DECIMAL(_), Values::TYPE(_)) => todo!(),
            (Values::DECIMAL(_), Values::NAME(_)) => todo!(),
            (Values::POINTER(_), Values::VOID) => todo!(),
            (Values::POINTER(_), Values::SIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::UNSIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::DECIMAL(_)) => todo!(),
            (Values::POINTER(_), Values::POINTER(_)) => todo!(),
            (Values::POINTER(_), Values::STRUCT) => todo!(),
            (Values::POINTER(_), Values::TYPE(_)) => todo!(),
            (Values::POINTER(_), Values::NAME(_)) => todo!(),
            (Values::STRUCT, Values::VOID) => todo!(),
            (Values::STRUCT, Values::SIGNED(_)) => todo!(),
            (Values::STRUCT, Values::UNSIGNED(_)) => todo!(),
            (Values::STRUCT, Values::DECIMAL(_)) => todo!(),
            (Values::STRUCT, Values::POINTER(_)) => todo!(),
            (Values::STRUCT, Values::STRUCT) => todo!(),
            (Values::STRUCT, Values::TYPE(_)) => todo!(),
            (Values::STRUCT, Values::NAME(_)) => todo!(),
            (Values::TYPE(_), Values::VOID) => todo!(),
            (Values::TYPE(_), Values::SIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::UNSIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::DECIMAL(_)) => todo!(),
            (Values::TYPE(_), Values::POINTER(_)) => todo!(),
            (Values::TYPE(_), Values::STRUCT) => todo!(),
            (Values::TYPE(_), Values::TYPE(_)) => todo!(),
            (Values::TYPE(_), Values::NAME(_)) => todo!(),
            (Values::NAME(_), Values::VOID) => todo!(),
            (Values::NAME(_), Values::SIGNED(_)) => todo!(),
            (Values::NAME(_), Values::UNSIGNED(_)) => todo!(),
            (Values::NAME(_), Values::DECIMAL(_)) => todo!(),
            (Values::NAME(_), Values::POINTER(_)) => todo!(),
            (Values::NAME(_), Values::STRUCT) => todo!(),
            (Values::NAME(_), Values::TYPE(_)) => todo!(),
            (Values::NAME(_), Values::NAME(_)) => todo!(),
        }
    }

    pub fn sub(&self, other: &Values) -> Values {
        match (self, other) {
            (Values::SIGNED(a), Values::SIGNED(b)) => Values::SIGNED(a - b),
            (Values::UNSIGNED(a), Values::UNSIGNED(b)) => Values::UNSIGNED(a - b),
            (Values::DECIMAL(a), Values::DECIMAL(b)) => Values::DECIMAL(a - b),
            (Values::SIGNED(a), Values::UNSIGNED(b)) => Values::SIGNED(*a - *b as i64),
            (Values::UNSIGNED(a), Values::SIGNED(b)) => Values::SIGNED(*a as i64 - *b),
            (Values::SIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 - b),
            (Values::UNSIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 - b),
            (Values::DECIMAL(a), Values::SIGNED(b)) => Values::DECIMAL(a - *b as f64),
            (Values::DECIMAL(a), Values::UNSIGNED(b)) => Values::DECIMAL(a - *b as f64),
            (Values::VOID, Values::VOID) => todo!(),
            (Values::VOID, Values::SIGNED(_)) => todo!(),
            (Values::VOID, Values::UNSIGNED(_)) => todo!(),
            (Values::VOID, Values::DECIMAL(_)) => todo!(),
            (Values::VOID, Values::POINTER(_)) => todo!(),
            (Values::VOID, Values::STRUCT) => todo!(),
            (Values::VOID, Values::TYPE(_)) => todo!(),
            (Values::VOID, Values::NAME(_)) => todo!(),
            (Values::SIGNED(_), Values::VOID) => todo!(),
            (Values::SIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::SIGNED(_), Values::STRUCT) => todo!(),
            (Values::SIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::SIGNED(_), Values::NAME(_)) => todo!(),
            (Values::UNSIGNED(_), Values::VOID) => todo!(),
            (Values::UNSIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::UNSIGNED(_), Values::STRUCT) => todo!(),
            (Values::UNSIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::UNSIGNED(_), Values::NAME(_)) => todo!(),
            (Values::DECIMAL(_), Values::VOID) => todo!(),
            (Values::DECIMAL(_), Values::POINTER(_)) => todo!(),
            (Values::DECIMAL(_), Values::STRUCT) => todo!(),
            (Values::DECIMAL(_), Values::TYPE(_)) => todo!(),
            (Values::DECIMAL(_), Values::NAME(_)) => todo!(),
            (Values::POINTER(_), Values::VOID) => todo!(),
            (Values::POINTER(_), Values::SIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::UNSIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::DECIMAL(_)) => todo!(),
            (Values::POINTER(_), Values::POINTER(_)) => todo!(),
            (Values::POINTER(_), Values::STRUCT) => todo!(),
            (Values::POINTER(_), Values::TYPE(_)) => todo!(),
            (Values::POINTER(_), Values::NAME(_)) => todo!(),
            (Values::STRUCT, Values::VOID) => todo!(),
            (Values::STRUCT, Values::SIGNED(_)) => todo!(),
            (Values::STRUCT, Values::UNSIGNED(_)) => todo!(),
            (Values::STRUCT, Values::DECIMAL(_)) => todo!(),
            (Values::STRUCT, Values::POINTER(_)) => todo!(),
            (Values::STRUCT, Values::STRUCT) => todo!(),
            (Values::STRUCT, Values::TYPE(_)) => todo!(),
            (Values::STRUCT, Values::NAME(_)) => todo!(),
            (Values::TYPE(_), Values::VOID) => todo!(),
            (Values::TYPE(_), Values::SIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::UNSIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::DECIMAL(_)) => todo!(),
            (Values::TYPE(_), Values::POINTER(_)) => todo!(),
            (Values::TYPE(_), Values::STRUCT) => todo!(),
            (Values::TYPE(_), Values::TYPE(_)) => todo!(),
            (Values::TYPE(_), Values::NAME(_)) => todo!(),
            (Values::NAME(_), Values::VOID) => todo!(),
            (Values::NAME(_), Values::SIGNED(_)) => todo!(),
            (Values::NAME(_), Values::UNSIGNED(_)) => todo!(),
            (Values::NAME(_), Values::DECIMAL(_)) => todo!(),
            (Values::NAME(_), Values::POINTER(_)) => todo!(),
            (Values::NAME(_), Values::STRUCT) => todo!(),
            (Values::NAME(_), Values::TYPE(_)) => todo!(),
            (Values::NAME(_), Values::NAME(_)) => todo!(),
        }
    }

    pub fn mul(&self, other: &Values) -> Values {
        match (self, other) {
            (Values::SIGNED(a), Values::SIGNED(b)) => Values::SIGNED(a * b),
            (Values::UNSIGNED(a), Values::UNSIGNED(b)) => Values::UNSIGNED(a * b),
            (Values::DECIMAL(a), Values::DECIMAL(b)) => Values::DECIMAL(a * b),
            (Values::SIGNED(a), Values::UNSIGNED(b)) => Values::SIGNED(*a * *b as i64),
            (Values::UNSIGNED(a), Values::SIGNED(b)) => Values::SIGNED(*a as i64 * *b),
            (Values::SIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 * b),
            (Values::UNSIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 * b),
            (Values::DECIMAL(a), Values::SIGNED(b)) => Values::DECIMAL(a * *b as f64),
            (Values::DECIMAL(a), Values::UNSIGNED(b)) => Values::DECIMAL(a * *b as f64),
            (Values::VOID, Values::VOID) => todo!(),
            (Values::VOID, Values::SIGNED(_)) => todo!(),
            (Values::VOID, Values::UNSIGNED(_)) => todo!(),
            (Values::VOID, Values::DECIMAL(_)) => todo!(),
            (Values::VOID, Values::POINTER(_)) => todo!(),
            (Values::VOID, Values::STRUCT) => todo!(),
            (Values::VOID, Values::TYPE(_)) => todo!(),
            (Values::VOID, Values::NAME(_)) => todo!(),
            (Values::SIGNED(_), Values::VOID) => todo!(),
            (Values::SIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::SIGNED(_), Values::STRUCT) => todo!(),
            (Values::SIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::SIGNED(_), Values::NAME(_)) => todo!(),
            (Values::UNSIGNED(_), Values::VOID) => todo!(),
            (Values::UNSIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::UNSIGNED(_), Values::STRUCT) => todo!(),
            (Values::UNSIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::UNSIGNED(_), Values::NAME(_)) => todo!(),
            (Values::DECIMAL(_), Values::VOID) => todo!(),
            (Values::DECIMAL(_), Values::POINTER(_)) => todo!(),
            (Values::DECIMAL(_), Values::STRUCT) => todo!(),
            (Values::DECIMAL(_), Values::TYPE(_)) => todo!(),
            (Values::DECIMAL(_), Values::NAME(_)) => todo!(),
            (Values::POINTER(_), Values::VOID) => todo!(),
            (Values::POINTER(_), Values::SIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::UNSIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::DECIMAL(_)) => todo!(),
            (Values::POINTER(_), Values::POINTER(_)) => todo!(),
            (Values::POINTER(_), Values::STRUCT) => todo!(),
            (Values::POINTER(_), Values::TYPE(_)) => todo!(),
            (Values::POINTER(_), Values::NAME(_)) => todo!(),
            (Values::STRUCT, Values::VOID) => todo!(),
            (Values::STRUCT, Values::SIGNED(_)) => todo!(),
            (Values::STRUCT, Values::UNSIGNED(_)) => todo!(),
            (Values::STRUCT, Values::DECIMAL(_)) => todo!(),
            (Values::STRUCT, Values::POINTER(_)) => todo!(),
            (Values::STRUCT, Values::STRUCT) => todo!(),
            (Values::STRUCT, Values::TYPE(_)) => todo!(),
            (Values::STRUCT, Values::NAME(_)) => todo!(),
            (Values::TYPE(_), Values::VOID) => todo!(),
            (Values::TYPE(_), Values::SIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::UNSIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::DECIMAL(_)) => todo!(),
            (Values::TYPE(_), Values::POINTER(_)) => todo!(),
            (Values::TYPE(_), Values::STRUCT) => todo!(),
            (Values::TYPE(_), Values::TYPE(_)) => todo!(),
            (Values::TYPE(_), Values::NAME(_)) => todo!(),
            (Values::NAME(_), Values::VOID) => todo!(),
            (Values::NAME(_), Values::SIGNED(_)) => todo!(),
            (Values::NAME(_), Values::UNSIGNED(_)) => todo!(),
            (Values::NAME(_), Values::DECIMAL(_)) => todo!(),
            (Values::NAME(_), Values::POINTER(_)) => todo!(),
            (Values::NAME(_), Values::STRUCT) => todo!(),
            (Values::NAME(_), Values::TYPE(_)) => todo!(),
            (Values::NAME(_), Values::NAME(_)) => todo!(),
        }
    }

    pub fn div(&self, other: &Values) -> Values {
        match (self, other) {
            (Values::SIGNED(a), Values::SIGNED(b)) => Values::SIGNED(a / b),
            (Values::UNSIGNED(a), Values::UNSIGNED(b)) => Values::UNSIGNED(a / b),
            (Values::DECIMAL(a), Values::DECIMAL(b)) => Values::DECIMAL(a / b),
            (Values::SIGNED(a), Values::UNSIGNED(b)) => Values::SIGNED(*a / *b as i64),
            (Values::UNSIGNED(a), Values::SIGNED(b)) => Values::SIGNED(*a as i64 / *b),
            (Values::SIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 / b),
            (Values::UNSIGNED(a), Values::DECIMAL(b)) => Values::DECIMAL(*a as f64 / b),
            (Values::DECIMAL(a), Values::SIGNED(b)) => Values::DECIMAL(a / *b as f64),
            (Values::DECIMAL(a), Values::UNSIGNED(b)) => Values::DECIMAL(a / *b as f64),
            (Values::VOID, Values::VOID) => todo!(),
            (Values::VOID, Values::SIGNED(_)) => todo!(),
            (Values::VOID, Values::UNSIGNED(_)) => todo!(),
            (Values::VOID, Values::DECIMAL(_)) => todo!(),
            (Values::VOID, Values::POINTER(_)) => todo!(),
            (Values::VOID, Values::STRUCT) => todo!(),
            (Values::VOID, Values::TYPE(_)) => todo!(),
            (Values::VOID, Values::NAME(_)) => todo!(),
            (Values::SIGNED(_), Values::VOID) => todo!(),
            (Values::SIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::SIGNED(_), Values::STRUCT) => todo!(),
            (Values::SIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::SIGNED(_), Values::NAME(_)) => todo!(),
            (Values::UNSIGNED(_), Values::VOID) => todo!(),
            (Values::UNSIGNED(_), Values::POINTER(_)) => todo!(),
            (Values::UNSIGNED(_), Values::STRUCT) => todo!(),
            (Values::UNSIGNED(_), Values::TYPE(_)) => todo!(),
            (Values::UNSIGNED(_), Values::NAME(_)) => todo!(),
            (Values::DECIMAL(_), Values::VOID) => todo!(),
            (Values::DECIMAL(_), Values::POINTER(_)) => todo!(),
            (Values::DECIMAL(_), Values::STRUCT) => todo!(),
            (Values::DECIMAL(_), Values::TYPE(_)) => todo!(),
            (Values::DECIMAL(_), Values::NAME(_)) => todo!(),
            (Values::POINTER(_), Values::VOID) => todo!(),
            (Values::POINTER(_), Values::SIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::UNSIGNED(_)) => todo!(),
            (Values::POINTER(_), Values::DECIMAL(_)) => todo!(),
            (Values::POINTER(_), Values::POINTER(_)) => todo!(),
            (Values::POINTER(_), Values::STRUCT) => todo!(),
            (Values::POINTER(_), Values::TYPE(_)) => todo!(),
            (Values::POINTER(_), Values::NAME(_)) => todo!(),
            (Values::STRUCT, Values::VOID) => todo!(),
            (Values::STRUCT, Values::SIGNED(_)) => todo!(),
            (Values::STRUCT, Values::UNSIGNED(_)) => todo!(),
            (Values::STRUCT, Values::DECIMAL(_)) => todo!(),
            (Values::STRUCT, Values::POINTER(_)) => todo!(),
            (Values::STRUCT, Values::STRUCT) => todo!(),
            (Values::STRUCT, Values::TYPE(_)) => todo!(),
            (Values::STRUCT, Values::NAME(_)) => todo!(),
            (Values::TYPE(_), Values::VOID) => todo!(),
            (Values::TYPE(_), Values::SIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::UNSIGNED(_)) => todo!(),
            (Values::TYPE(_), Values::DECIMAL(_)) => todo!(),
            (Values::TYPE(_), Values::POINTER(_)) => todo!(),
            (Values::TYPE(_), Values::STRUCT) => todo!(),
            (Values::TYPE(_), Values::TYPE(_)) => todo!(),
            (Values::TYPE(_), Values::NAME(_)) => todo!(),
            (Values::NAME(_), Values::VOID) => todo!(),
            (Values::NAME(_), Values::SIGNED(_)) => todo!(),
            (Values::NAME(_), Values::UNSIGNED(_)) => todo!(),
            (Values::NAME(_), Values::DECIMAL(_)) => todo!(),
            (Values::NAME(_), Values::POINTER(_)) => todo!(),
            (Values::NAME(_), Values::STRUCT) => todo!(),
            (Values::NAME(_), Values::TYPE(_)) => todo!(),
            (Values::NAME(_), Values::NAME(_)) => todo!(),
        }
    }
}